openapi: 3.0.1
info:
  title: BadSheet API
  description: >-
    Backend for the app BadSheet to get team and player information from
    turnier.de
  version: 0.0.1
servers:
  - url: http://62.113.204.221/v1
paths:
  /teams:
    get:
      summary: Returns a list of all teams.
      responses:
        '200':
          description: A JSON array of all teams.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
    post:
      summary: Updates the list of teams in the backend.
      responses:
        '202':
          description: All teams are updated.
  /players/{teamname}:
    get:
      summary: Returns all players of a team.
      parameters:
        - name: teamname
          in: path
          description: Name of the team.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A JSON array of all players.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'

components:
  schemas:
    Team:
      type: object
      required:
        - name
        - id
      properties:
        name:
          type: string
        id:
          type: integer
    Player:
      type: object
      required:
        - name
        - sex
      properties:
        name:
          type: string
        sex:
          type: string
          enum:
            - male
            - female